### ISSUE TITLE
Is there any other version of the data download link, such as Baidu Netdisk or Google Cloud Disk？

### ISSUE THREAD

**Issue by JackeyWeng** [gaiasd/d-fire#1]

**Comment by pedbrgs** [comment]
Unfortunately not, @JackeyWeng.
Apologies for the delayed response.

**Comment by pedbrgs** [comment]
@JackeyWeng Now we have the dataset available on Google Drive. Check [here](https://drive.google.com/drive/folders/1DWgsQLVgkkLM8m-VcugHNpD5WYDbjYp5).

**Comment by JackeyWeng** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮件我已收到。我会尽快回复或者转发。祝好！
